# Intern Details
* Name: Omeh Chukwuemeka
* Track: Data Science
* Email: chukwuemekao241@gmail.com

# Importing Necessary Libraries

In [1]:
import pandas as pd
import numpy as np

# Loading Dataset

In [2]:
data_url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
fuel_data = pd.read_csv(data_url)

print(f"The dataset have {fuel_data.shape[0]} rows and {fuel_data.shape[1]} columns")

The dataset have 29523 rows and 11 columns


In [3]:
fuel_data.head(n = 6)

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   
5  f1_fuel_1994_12_2_0_13                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   
5   e. c. gaston-unit 5                coal       ton        2124933.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   
5               23.922                      44.24   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570  
5                         43.25                1.850

In [4]:
fuel_data.dtypes

record_id                        object
utility_id_ferc1                  int64
report_year                       int64
plant_name_ferc1                 object
fuel_type_code_pudl              object
fuel_unit                        object
fuel_qty_burned                 float64
fuel_mmbtu_per_unit             float64
fuel_cost_per_unit_burned       float64
fuel_cost_per_unit_delivered    float64
fuel_cost_per_mmbtu             float64
dtype: object


# Question 1

If you’re given two lists:

A = [1,2,3,4,5,6], B = [13, 21, 34]

The task is to create a list with the elements of A and B in a single dimension with output:

A_B = [1,2,3,4,5,6,13, 21, 34]

Which of the following option is the best way to create this list?


In [5]:
A = [1,2,3,4,5,6]
B = [13,21,34]
A.extend(B)
A_B = A
print(A_B)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


# Question 2

How do you create an identity matrix in python?

In [6]:
# A 3 x 3 Identity matrix 

identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 3¶

Which of the following fuel type code has the lowest average fuel cost per unit burned?

In [7]:
# Ans = Gas
fuel_type_average = dict(fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean())
print(f"The fuel type code with lowest average fuel cost per unit burned is: {min(fuel_type_average, key=fuel_type_average.get)}")

The fuel type code with lowest average fuel cost per unit burned is: gas


In [8]:
fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean().sort_values(ascending = False)

fuel_type_code_pudl
nuclear    4955.157002
oil         168.877086
coal         67.421830
waste        19.518122
other        18.253856
gas          13.659397
Name: fuel_cost_per_unit_burned, dtype: float64

# Question 4

What is the standard deviation and 75th percentile of the measure of energy per unit (Fuel_mmbtu_per_unit) in two decimal places?

In [9]:
summary_stats = fuel_data["fuel_mmbtu_per_unit"].describe()
print(f"The standard deviation for fuel_mmbtu_per_unit is: {summary_stats['std'].round(2)}")
print(f"The 75th percentile for fuel_mmbtu_per_unit is: {summary_stats['75%'].round(2)}")

The standard deviation for fuel_mmbtu_per_unit is: 10.6
The 75th percentile for fuel_mmbtu_per_unit is: 17.01


# Question 5

What is the skewness and kurtosis for the fuel quantity burned in two decimal places?

In [10]:
skewness_fuel_qty_burned = fuel_data["fuel_qty_burned"].skew()
kurtosis_fuel_qty_burned = fuel_data["fuel_qty_burned"].kurt()

print(f"The skewness of fuel_qty_burned is: {round(skewness_fuel_qty_burned, 2)}")
print(f"The kurtosis of fuel_qty_burned is: {round(kurtosis_fuel_qty_burned, 2)}")

The skewness of fuel_qty_burned is: 15.85
The kurtosis of fuel_qty_burned is: 651.37


# Question 6

Which feature has missing values and what is the total number of missing value and percentage of the missing rows as a factor of the total number of rows in three decimal places?

(Enter answer in the format: Feature: xxx, Total: xxx, Percent: xxx)

In [11]:
fuel_data.isna().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [12]:
# PERCENTAGE OF MISSING VALUES == 0.610 in 3 decimal places
missing_column = "fuel_unit"
print(f"The number of missing values in fuel_unit column is: {fuel_data[missing_column].isnull().sum()}")
print(f"The total number of rows of fuel_unit column is: {fuel_data[missing_column].shape[0]}")
print("The percentage of missing values is: 0.610",'\n',round(fuel_data[missing_column].isna().value_counts(normalize = True)*100,3))

The number of missing values in fuel_unit column is: 180
The total number of rows of fuel_unit column is: 29523
The percentage of missing values is: 0.610 
 False    99.39
True      0.61
Name: fuel_unit, dtype: float64


In [13]:
# WE CAN ALSO FIND PERCENTAGE OF MISSING VALUE USING BELOW APPROACH
missing_values = fuel_data.fuel_unit.isnull().sum()
print(f'The Number of Missing Values is: {missing_values}')
print(f'The Total Number of rows of fuel_unit is: {fuel_data.fuel_unit.shape[0]}')
percentage_missing_value = (missing_values / fuel_data.fuel_unit.shape[0]) * 100
print(f'The Percentage of missing values in fuel_unit column is:{round(percentage_missing_value, 3)}')

The Number of Missing Values is: 180
The Total Number of rows of fuel_unit is: 29523
The Percentage of missing values in fuel_unit column is:0.61


# Question 7

The feature with missing values falls under what category? What missing value imputation technique would you use?

In [14]:
column = fuel_data.columns
for col in column:
    if fuel_data[col].isnull().any():
        print(f"THE MISSING VALUE FALL UNDER THE {fuel_data[col].dtypes} DATA TYPE", '\n')
print("========================================================================================================", '\n')
print("THE MISSING VALUE IMPUTATION TECHNIQUES FOR CATEGORICAL/OBJECT DATA TYPES IS: MODE(MOST FREQUENT)",'\n', fuel_data.fuel_unit.mode())

#fuel_data[[ 'fuel_unit' ]] = fuel_data[[ 'fuel_unit' ]].fillna(value= 'mcf')

THE MISSING VALUE FALL UNDER THE object DATA TYPE 


THE MISSING VALUE IMPUTATION TECHNIQUES FOR CATEGORICAL/OBJECT DATA TYPES IS: MODE(MOST FREQUENT) 
 0    mcf
dtype: object


# Question 8

Which of the features has the second and third lowest correlation with the Fuel Cost Per Unit Burned?

In [15]:
print("==========THE SECOND AND THIRD LOWEST CORRELATION WITH FUEL COST PER UNIT BURNED IS==========")
fuel_data.corrwith(other = fuel_data["fuel_cost_per_unit_burned"], method = 'pearson').sort_values()[1:3]

==========THE SECOND AND THIRD LOWEST CORRELATION WITH FUEL COST PER UNIT BURNED IS==========


fuel_qty_burned       -0.018535
fuel_mmbtu_per_unit   -0.010034
dtype: float64

# Question 9

For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994?

In [16]:
condition_1 = ((fuel_data["fuel_type_code_pudl"] == 'coal') & (fuel_data["report_year"] == 1994))
condition_2 = ((fuel_data["fuel_type_code_pudl"] == 'coal') & (fuel_data["report_year"] == 1998))

year_1994 = fuel_data[condition_1]["fuel_cost_per_unit_burned"].sum()
year_1998 = fuel_data[condition_2]["fuel_cost_per_unit_burned"].sum()
print(f"The Total Coal fuel cost per unit burned in year 1994 is: {year_1994}")
print(f"The Total Coal fuel cost per unit burned in year 1998 is: {year_1998}" ,'\n')

print("=================PERCENTAGE CHANGE============",'\n')

percentage_change = ((year_1998 - year_1994) /year_1994)*100

print(f"THE PERCENTAGE CHANGE OF FUEL COST PER UNIT BURNED IN 1998 COMPARED TO 1994 IS: {round(percentage_change)}%")

The Total Coal fuel cost per unit burned in year 1994 is: 14984.572
The Total Coal fuel cost per unit burned in year 1998 is: 11902.597 

=================PERCENTAGE CHANGE============ 

THE PERCENTAGE CHANGE OF FUEL COST PER UNIT BURNED IN 1998 COMPARED TO 1994 IS: -21%


# Question 10

Which year has the highest average fuel cost per unit delivered?

In [17]:
fuel_cost_unit_delivered_avg = dict(fuel_data.groupby("report_year")["fuel_cost_per_unit_delivered"].mean())
print(f"The year with highest average fuel cost per unit delivered is: {max(fuel_cost_unit_delivered_avg, key = fuel_cost_unit_delivered_avg.get)}")

The year with highest average fuel cost per unit delivered is: 1997


In [18]:
fuel_data.groupby("report_year")["fuel_cost_per_unit_delivered"].mean().sort_values(ascending = False)

report_year
1997    11140.197239
1996     9196.705948
2000      985.362877
2009      652.694163
2018      499.269966
2015      326.535511
1998      287.154420
2014      192.737183
2013      172.307591
2004      139.524275
2016      103.901761
2010       91.862105
1994       63.636060
2012       60.994502
2001       60.050396
2011       59.774667
2008       58.588197
2003       55.663493
2002       47.594361
2017       46.196861
2007       43.325023
2005       41.438184
2006       38.657484
1995       32.735269
1999       25.551627
Name: fuel_cost_per_unit_delivered, dtype: float64

# THE END